[package]
name = "loader"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
object = { version = "0.37", default-features = false, features = ["elf", "unaligned", "read", "std"] }
rand = "0.9"
rtenv = { path = "../rtenv" }
structures = { path = "../structures" }
