[package]
name = "syscall"
version = "0.0.1"
edition = "2024"

[dependencies]
libc = "0.2"
log = "0.4"
structures = { path = "../structures" }
rtenv = { path = "../rtenv" }
macros = { path = "../macros" }
rustc-hash = "2"
