[package]
name = "syscall"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
structures = { path = "../structures" }
rtenv = { path = "../rtenv" }
macros = { path = "../macros" }
rustc-hash = "2"
